import { Button } from "@components/ui/button";
import { BookOpenIcon, HomeIcon, UserIcon } from "@heroicons/react/24/outline";
import "@styles/global.css";
import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${redHatDisplay.className} flex flex-row h-screen`}>
        <div className="flex flex-col w-80 bg-backgroundSidebar text-primary p-5">
          <h1 className="text-xl">
            <b>Latte Corporation</b>
          </h1>
          <div className="flex flex-col justify-between h-full">
            <nav className="mt-10 flex flex-col gap-4">
              <Button className="flex flex-row items-center justify-start gap-1 h-14">
                <HomeIcon className="h-7 w-7" />
                <h2 className="pl-3 text-base">Home</h2>
              </Button>
              <Button className="flex flex-row items-center justify-start gap-1 h-14">
                <BookOpenIcon className="h-7 w-7" />
                <h2 className="pl-3 text-base">Portfolio</h2>
              </Button>
              <Button className="flex flex-row items-center justify-start gap-1 h-14">
                <UserIcon className="h-7 w-7" />
                <h2 className="pl-3 text-base">Contact</h2>
              </Button>
            </nav>
            <Button className="bg-[#E6CCB2] h-14">Request a demo</Button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
